<?php
/**
 * Created by PhpStorm.
 * User: xujing
 * Date: 2016/6/29
 * Time: 8:43
 * Description
 */
namespace Website\Controller;

class ContactsController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow(array('lists'));
    }

    protected function _setPaginate($order = array('id' => 'asc'), $fields = array(), $contain = array())
    {
        $page = $this->request->data('page') ? : 1;
        $this->paginate = array(
            'limit' => 10,
            'page' => $page,
            'order' => $order,
            'fields' => $fields,
            'contain' => $contain
        );
    }

    public function lists()
    {
        $this->viewBuilder()->layout('front');
        $this->_setPaginate();
        $contacts = $this->paginate($this->Contacts)->toArray();
        $this->set(compact('contacts'));
        if ($this->request->is('ajax')) {
            $this->viewBuilder()->className('Json');
            $this->set('_serialize', array('contacts'));
        }
    }

    public function getData()
    {
        die('dasd');
    }

}