<?php
/**
 * Created by PhpStorm.
 * User: xujing
 * Date: 2016/6/29
 * Time: 8:43
 * Description
 */
namespace Website\Controller;

use Cake\ORM\TableRegistry;

class NoticesController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow(array('lists'));
    }

    protected function _setPaginate($order = array('created' => 'desc'), $fields = array(), $contain = array('Items'))
    {
        $page = $this->request->data('page') ? : 1;
        $this->paginate = array(
            'limit' => 10,
            'page' => $page,
            'order' => $order,
            'fields' => $fields,
            'contain' => $contain
        );
    }

    public function lists($item_id = null)
    {
        $conditions = array();
        $this->viewBuilder()->layout('front');
        $this->_setPaginate();

        if (isset($item_id) && !empty($item_id)) {
            $conditions['Notices.item_id'] = $item_id;
        }

        $noticeModel = TableRegistry::get('Phetom.Notices');
        $query = $noticeModel->find()->where($conditions);
        $notices = $this->paginate($query)->toArray();
        $user_id = $this->Auth->user('id');

        $typeData = $noticeModel->typeData();
        $typeclassData = array(
            '1' => 'label-info',
            '2' => 'label-danger',
            '3' => 'label-success'
        );

        foreach($notices as $key => $val) {
            $notices[$key]->created = date('Y-m-d H:i', strtotime($val->created));
            $notices[$key]->url = '/website/notices/info/'.$val->id;
            $isViewData = explode(',', $val->is_view);
            $notices[$key]->isview = '未读';
            if (in_array($user_id, $isViewData)) {
                $notices[$key]->isview = '已读';
            }

            $notices[$key]->typename = $typeData[$val->type];
            $notices[$key]->typeclass = $typeclassData[$val->type];
        }

        $this->set(compact('notices', 'item_id'));

        if ($this->request->is('ajax')) {
            $this->viewBuilder()->className('Json');
            $this->set('_serialize', array('notices'));
        }
    }


    /*
     * 查看通知
     *
     * */
    public function info($id = null) {
        $this->viewBuilder()->layout('front');
        $data = TableRegistry::get('Phetom.Notices')->get($id, [
            'contain' => ['Items']
        ]);

        $isViewArr = explode(',', $data->is_view);
        if (!in_array($this->Auth->user('id'), $isViewArr)) {
            $updateData['is_view'] = $data->is_view .','.$this->Auth->user('id');
            $data = $this->Notices->patchEntity($data, $updateData);
            TableRegistry::get('Phetom.Notices')->save($data);
        }
        $this->set(compact('data'));
    }
}