<?php
/**
 * Created by PhpStorm.
 * User: xujing
 * Date: 2016/6/22
 * Time: 13:42
 * Description
 */
namespace App\Controller;

class WelcomeController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow('index');
    }

    /*
     * system center
     */
    public function index()
    {
        die('This is a system center');
    }
}