<?php
/**
 * Created by PhpStorm.
 * User: xujing
 * Date: 2016/6/28
 * Time: 10:52
 * Description
 */
namespace App\Model\Table;

use Cake\ORM\Entity;
use Cake\ORM\Table;
use Cake\Utility\Hash;

class ItemsTable extends Table
{
    /*
     *
     */
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->table('items');

        $this->hasMany('Streets', array(
            'className' => 'Website.Streets',
            'foreignKey' => 'item_id'
        ));
    }

    /*
     * 转换数据格式
     * @param
     */
    public function toJson($data, $fields = array()) {
        if (empty($fields)) {
            $fields = $this->schema()->columns();
        }
        $i = 0;
        $result = array();
        foreach ($data as $item) {
            if ($item instanceof Entity) {
                $item = $item->toArray();
            }
            foreach ($fields as $field) {
                if (isset($item[$field])) {
                    $result[$i][$field] = $item[$field];
                }
            }
            $i++;
        }
        return json_encode($result);
    }

    /*
     * 获取正在建设的项目
     */
    public function getOkData()
    {
        $items = $this->find()
            ->select(array('id', 'state', 'longitude', 'latitude', 'name', 'intro', 'image', 'currentTime'))
            ->where(array('ok' => 1))
            ->contain(array('Streets'))
            ->map(function($row) {
                if (!is_file($row->image)) {
                    $row->image = 'images/item.png';
                }
                return $row;
            })
            ->map(function($row) {
//                $streets = $row->streets;
//                $row->area = Hash::extract($streets->toArray(), '{n}.id');
                $area = array();
                foreach ($row->streets as $street) {
                    $area[] = $street->area_id;
                }
                $row->area = $area;
                return $row;
            })
            ->toArray();
        $result = $this->toJson($items, array('id', 'state', 'longitude', 'latitude', 'name', 'intro', 'image', 'area', 'currentTime'));
        return $result;
    }
}